GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Gather.cs, GatherBuddy/AutoGather/AutoGather.Ui.cs, GatherBuddy/AutoGather/AutoGather.Var.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/Gui/Interface.DebugTab.cs
Extra display lines have been added to show item integrity in the debug and UI windows. The collectability-based function calls have been updated to also evaluate integrity before taking an action. Also, measures have been taken to prevent possible issues when more than one desired item is in the Zone.
=> Add integrity checks and display for AutoGather

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/CustomInfo/FuzzyVector3.cs
The code has been refactored by adding throttle checks to various parts to prevent them from being executed too frequently. A bug in the AutoGather feature that caused the character to move before the required GP had fully regenerated has been fixed. This bug was causing a failed gathering attempt, now the character will wait till the required GP regenerates.
=> Refactor code and fix movement bug in AutoGather feature

GatherBuddy/AutoGather/AutoGather.Var.cs
Added a new method GatherableMatchesJob to filter Gatherable items that match the job type. This method is used within the existing expression for retrieving ItemsToGatherInZone. This ensures that only appropriate items are gathered based on the current job.
=> Add filter to only gather items matching job type

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
Added two new options to the auto-gathering feature:
- Gather instead losing the node
- Minimum collectibility score to reach before gathering on the last integrity point
I also changed the "Minimum Collectibility Score" to "Collectibility score to reach before gathering" because I wasn't sure at first what it really meant.
The new feature let us chose to collect the node even if the selected collectible didn't reach the collectibility score that has been set. Optionally, we can set another minimum collectible value for this specific feature :
_the second slider is hidden if the checkbox is unchecked_
In this example, if the collectible reached the score of 700 but only has one remaining integrity point, it will be gathered instead of trying to increase the value again and probably losing …
=> Added collectible gathering on the last integrity point

GatherBuddy/AutoGather/AutoGather.Actions.cs
For high GP collectible rotation where Solid / Ageless can be used multiple times, the current code prioritizes use Solid / Ageless despite having Eureka Moment buff active, causing wasted Wise actions. The code changes to ShouldUseSolidAge function now checks that Eureka Moment buff is inactive before using Solid / Ageless.
=> Fix Eureka Moment buff overwriting by Solid / Ageless

GatherBuddy/AutoGather/AutoGather.Actions.cs
I made 2 lists: one for Bountiful Yield buffs and one for Kings Yield buffs. It also happens that KYI and KYII buffs have the same id.
=> Fixed Bountiful Yield II being blocked by King's Yield buff

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
Reworked the Collectables actions conditions and logic to improve decision making and allow to choose when to do a full collect rotation.
- Removed specific conditions from the collectable actions.
- Added a class to handle the rotations. It's made with multiple rotations in mind so we can improve it with other rotations and a choice in the config later.
- Also fixed a bug in config where Meticulous min GP slider was linked to Luck min GP
=> Reworked the Collectables actions logic

GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.Consumables.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/AutoGather/AutoGather.Ui.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/Gui/Interface.ConfigTab.cs, GatherBuddy/Gui/Interface.DebugTab.cs
The consumables feature should be functional based on my own testing, though the code organization may not align with your needs. You may refactor it after testing that the features are indeed working correctly.
1. `AutoGather.Config.cs`: Added ConsumableConfig class to hold consumables configuration data.
2. `AutoGather.Consumables.cs`: Added new file to hold most consumables logic.
3. `AutoGather.Movement.cs`: Some consumables have cast time and can only be used while unmounted. I can't find a good spot to insert into `AutoGather.cs` where the player is guaranteed to be unmounted, and I didn't want to trigger unmounting in case it breaks navigation. Hence, I inserted one line into `AutoGather.Movement.cs` just before the player starts gathering a node. Please adjust this logic if …
=> Added consumables feature

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Gather.cs, GatherBuddy/AutoGather/AutoGather.cs
- I reworked the queuing / throttling during gathering to make sure we never queue an action while already doing a gather action.
- Delay is now minimal (250ms instead of 2000ms previously), and only used during collectable actions. The issue there was scrutiny making the player go in and out of Gathering42 condition very quickly, waiting a few frames before checking the condition fixed the issue. 
- Probably needs a bit of testing but I've been runing it all afternoon yesterday with the Prints I commented in the code, and didn't get a single action being used out of place / during another action.
=> Improved gather action queuing and waits

GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
1) Option to use Solid Reason / Ageless Words when you are lucky enough to hit the target collectability rating with the filler rotation.
2) Always use Brazen if Collector's High Standard is up (this was true only for filler rotation).
3) Merge FillerRotation() and FullRotation() into one.
=> Minor collectables improvements

GatherBuddy/CustomInfo/WorldData.cs
I've noticed that the locally saved node_offsets.json file is not merged with the bundled one. This patch fixes that.
=> Merge local and bundled node_offsets.json files

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.Consumables.cs, GatherBuddy/AutoGather/AutoGather.Gather.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/AutoGather/AutoGather.Spiritbond.cs, GatherBuddy/AutoGather/AutoGather.Ui.cs, GatherBuddy/AutoGather/AutoGather.Var.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/CustomInfo/FuzzyVector3.cs, GatherBuddy/GatherHelper/GatherWindowManager.ManipPreset.cs, GatherBuddy/GatherHelper/GatherWindowPreset.cs, GatherBuddy/Gui/Interface.ConfigTab.cs, GatherBuddy/Gui/Interface.DebugTab.cs, GatherBuddy/Gui/Interface.GatherGroupTab.cs, GatherBuddy/Gui/Interface.GatherWindowTab.cs, GatherBuddy/Plugin/IpcSubscribers.cs, GatherBuddy/Plugin/UptimeManager.cs
- Use luck for treasure maps. https://github.com/FFXIV-CombatReborn/GatherBuddyReborn/issues/192
- Don't try to overcap crystals and treasure maps. https://github.com/FFXIV-CombatReborn/GatherBuddyReborn/issues/182
- Don't use skills if a node doesn't have any item from the gathering list.
- Don't use Luck if hidden items are already revealed.
- Switch to the next item if the node has it and we have enough of the current one.
- Don't try to gather treasure maps if there is no map allowance.
- Abort when can't gather any items from the node.
- Abort when inventory is full.
- Extract materia before moving to the next node (like humans do).
- Dismount before waiting for GP to regenerate.
- Track visited timed nodes on a per-location basis. …
=> QoL improvements and fixes for some corner cases

GatherBuddy.GameData/Classes/Gatherable.cs, GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.Consumables.cs, GatherBuddy/AutoGather/AutoGather.Gather.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/AutoGather/AutoGather.Spiritbond.cs, GatherBuddy/AutoGather/AutoGather.Ui.cs, GatherBuddy/AutoGather/AutoGather.Var.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/AutoGather/GatheringTracker.cs, GatherBuddy/CustomInfo/FuzzyVector3.cs, GatherBuddy/GatherHelper/GatherWindowManager.ManipPreset.cs, GatherBuddy/GatherHelper/GatherWindowPreset.cs, GatherBuddy/Gui/Interface.ConfigTab.cs, GatherBuddy/Gui/Interface.DebugTab.cs, GatherBuddy/Gui/Interface.GatherGroupTab.cs, GatherBuddy/Gui/Interface.GatherWindowTab.cs, GatherBuddy/Plugin/IpcSubscribers.cs, GatherBuddy/Plugin/UptimeManager.cs
Introducing the GatheringTracker class. It uses the AddonLifecycle interface to listen for Setup and Refresh events of the Gathering addon, extracts all useful data from the AddonArgs, and provides a clean API to access this data. This way we can access much more data than provided by FFXIVClientStructs's AddonGathering, e.g., quick gathering states, item flags (hidden, rare, bonus), detecting disabled items (not meeting perception requirements). All data is obtained in the original integer form (no need to parse text nodes).
P.S. This is the continuation of my qol-improvements branch; therefore, the first 40 commits are described in this pull request: https://github.com/FFXIV-CombatReborn/GatherBuddyReborn/pull/198
=> Use AddonLifecycle to get data about a current gathering node

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Gather.cs, GatherBuddy/AutoGather/AutoGather.cs
Bugfixes:
- Fix collectable abilities are used incorrectly in the Japanese client.
- Fix fallback presets are not working.
- Fix navigating to a flag of a completely different node when precognition is high and two timed nodes are spawned in the current location in succession.
- Fix GBR stuck in the idle state when there is only one timed item in the list.
Changes:
- Apply execution delay after executing an action, not before. This should prevent incorrect skill usage when ping is high.
=> Qol improvements

GatherBuddy/GatherBuddyReborn.yaml
Bumps the `DalamudApiLevel` to 11 in the GatherBuddyReborn.yaml. 
Most likely doesn't matter with how the plugin is built by github actions, but probably best to still do
=> Bump DalamudApiLevel to 11

GatherBuddy/AutoGather/AutoGather.Var.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/AutoGather/Helpers/AdvancedUnstuck.cs
Path_IsRunning() and Nav_PathfindInProgress() may both return false in the moment right after pathfinding is completed. Advanced Unstuck treats this condition as vnavmesh failure. Avoid unnecessary activation of Advanced Unstuck by treating this condition as failure only if it persists for two framework updates.
=> Workaround for race condition in vnavmesh IPC

GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
GBR may sometimes be stuck with an open gathering window when gathering collectables. If the player clicks the collectable manually, the game crashes. This happens because sometimes after gathering collectables in a node, the GatheringMasterpiece addon would not close and continue to linger in the memory but invisible. What causes this is unknown.
This patch will detect the erroneous condition and stop Auto-Gather or, if the corresponding option is enabled, attempt to Close() the addon.
While testing, I've reproduced the issue thrice. The first time, after closing the addon, the issue repeated again and again until the game was restarted. The second and third time, the issue disappeared after the first Close().
=> Experimental fix for lingering GatheringMasterpiece addon

GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/AutoGather/Helpers/AdvancedUnstuck.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
Navigation is pretty much unusable without it, and many reported issues with navigation were actually due to advanced unstuck being disabled.
=> Proposal: remove the option to disable advanced unstuck

GatherBuddy/AutoGather/AutoGather.ActionIDs.cs, GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Var.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/AutoGather/ConfigPreset.cs, GatherBuddy/AutoGather/Helpers/RotationSolver.cs, GatherBuddy/GatherBuddy.cs, GatherBuddy/GatherHelper/GatherWindow.Ui.cs, GatherBuddy/Gui/Interface.ConfigPresetsTab.cs
Bringing Plug&Play into the GBR.
This patch adds the new "Automatically decide what actions to use" option, which will do the following:
- For collectables: the usual collectable rotation is used with all actions enabled.
- For unspoiled and legendary nodes: choose actions to maximise the yield.
- For regular nodes: choose actions to maximise the yield per GP spent. This mode also has a subotion to hold off spending GP until a node with a good enough bonuses is encountered.
Action sequences are discovered by the new RotationSolver class, which just tries out every possible sequence and returns the best one while also using some heuristics for corner cases.
This is still WIP: I need to implement the calculation of the gathering boon chance, and caching of solutions wouldn't hurt too. But …
=> Rotation solver

GatherBuddy/Config/Configuration.cs, GatherBuddy/GatherHelper/GatherWindow.Ui.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
I tend to have large auto gather lists that take up the entire side of my screen, so I was motivated to add a configuration option similar to the one in Teamcraft's List View to hide completed items, as there is already logic present to color completed items with a grey color.
=> Add configuration option to hide completed items from the gather window.

GatherBuddy/AutoGather/AutoGather.ActionIDs.cs, GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.Gather.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/AutoGather/AutoGather.Purify.cs, GatherBuddy/AutoGather/AutoGather.Spiritbond.cs, GatherBuddy/AutoGather/AutoGather.Ui.cs, GatherBuddy/AutoGather/AutoGather.Var.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/AutoGather/ConfigPreset.cs, GatherBuddy/AutoGather/Extensions/GatherableExtensions.cs, GatherBuddy/AutoGather/Helpers/AdvancedUnstuck.cs, GatherBuddy/AutoGather/Helpers/DiscipleOfLand.cs, GatherBuddy/AutoGather/Helpers/RotationSolver.cs, GatherBuddy/AutoGather/Lists/ActiveItemList.cs, GatherBuddy/AutoGather/Lists/AutoGatherListsManager.cs, GatherBuddy/GatherBuddy.cs, GatherBuddy/GatherHelper/GatherWindow.Ui.cs, GatherBuddy/Gui/Interface.AutoGatherTab.cs, GatherBuddy/Gui/Interface.ConfigPresetsTab.cs, GatherBuddy/Gui/Interface.ConfigTab.cs, GatherBuddy/Gui/Interface.DebugTab.cs, GatherBuddy/Plugin/GatherBuddyIpc.cs, GatherBuddy/Plugin/IpcSubscribers.cs
- Use a callback to close MaterializeAddon .
- Ignore mesh correction when the result is too far from the node (>0.5 yalms of max).
- Remove lingering GatheringMasterpiece addon detection.
- Add a perception check before gathering a node.
- Ignore items and locations that can't be gathered at the current job level.
- When sorting by location is enabled, prioritize items within the current location by distance to the player; otherwise, sort by teleportation cost.
- For items with multiple nodes, prioritize the current territory (and choose the closest nodes within it), then prioritize the cheapest Aetheryte or the node closest to its nearest Aetheryte, depending on settings.
- Change jobs after teleportation, not before.
- Implement automatic aetherial reduction triggered when fewer than …
=> Fixes and QoL improvements

GatherBuddy/AutoGather/Lists/AutoGatherList.cs, GatherBuddy/AutoGather/Lists/AutoGatherListsManager.ManipPreset.cs, GatherBuddy/AutoGather/Lists/AutoGatherListsManager.cs, GatherBuddy/Gui/Interface.AutoGatherTab.cs
Introduced individual item enable/disable control within AutoGather lists, allowing users to toggle items dynamically. Updated associated logic, GUI, and configuration data to support this feature, including migration for backward compatibility.
=> Add per-item enable/disable functionality to AutoGather lists

GatherBuddy/AutoGather/AutoGather.cs
Moved the gathering buffs activation logic to occur after gear set changes. This ensures buffs are applied under the correct conditions and aligns with the appropriate execution order for improved reliability.
=> Refactor gathering buff activation sequence.

GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
Introduced a new `LifestreamCommand` property to allow customization of the default command executed when idle or done gathering. Updated the UI to include a text input for modifying this command and adjusted logic to ensure commands are properly formatted before execution.
=> Add configurable Lifestream command for custom usage

GatherBuddy/AutoGather/AutoGather.Spiritbond.cs
Introduce a randomized delay between 500ms and 2000ms during the materia extraction process to reduce predictability. This enhances flexibility and can help avoid potential synchronization issues.
=> Add random delay to materia extraction task queue

GatherBuddy/AutoGather/Lists/AutoGatherList.cs
Updated the upper limit for item quantity from 9999 to 999999 to accommodate larger numbers. Ensured the restriction for treasure maps remains unchanged.
=> Increase max quantity limit to 999999.

.github/workflows/publish.yaml
Split the `publish.yaml` workflow into distinct `Plugin` and `Web` jobs for better clarity and organization. Moved Docker setup and container registry login exclusively to the `Web` job. Updated the `Plugin` job to handle plugin publishing using `softprops/action-gh-release`.
=> Refactor CI workflow to separate plugin and web jobs

GatherBuddy.Web/Controllers/ApiKeyAuthFilter.cs
Improved the log message for missing API keys by checking the "X-Forwarded-For" header before falling back to the connection's remote IP address. This ensures more accurate identification of the client source in proxied environments.
=> Refine API key logging

.github/workflows/publish.yaml, .gitignore, GatherBuddy.SecretKeys/SecretKeys.generated.cs, GatherBuddy.Web/GatherBuddy.Web.csproj, GatherBuddy.Web/Program.cs
Deleted the `SecretKeys.generated.cs` file containing a hardcoded API key for security reasons and added it to `.gitignore`. Adjusted the build command in the GitHub Actions workflow to use proper syntax for secret injection. Minor formatting cleanup in other project files.
=> Remove hardcoded API key and update build process.

GatherBuddy.SecretKeys/GatherBuddy.SecretKeys.csproj
Changed the build process to include `SecretKeys.generated.cs` by modifying the project file. Adjusted the `GenerateSecretKeys` target to run before the build instead of before compile, ensuring the file is ready during the build phase.
=> Update build process to include generated secret keys file

.github/workflows/publish.yaml
Introduce a new `KeyGen` job to generate a secret key using OpenSSL. The generated key is masked and set as an output for dependent jobs (`Plugin` and `Web`). This ensures a secure way to handle dynamically generated secrets in the CI pipeline.
=> Add key generation step to publish workflow

.github/workflows/publish.yaml
Replaced `secrets.GITHUB_TOKEN` with `env.SECRET_KEY` in build and deployment steps to utilize the correct secret environment variable. This ensures consistency and proper usage of the defined environment secrets.
=> Update secret key reference in publish workflow

.github/workflows/publish.yaml
Included SECRET_KEY in the environment configurations for both Windows and Ubuntu-latest jobs. This ensures the workflows have access to the generated key where necessary during execution.
=> Add SECRET_KEY to workflow environment variables

.github/workflows/publish.yaml
Replaced deprecated `set-output` command with `$GITHUB_OUTPUT` for secure output handling. Ensured consistent naming of job dependencies by changing `generate_key` to `KeyGen` in related uses. These changes improve compatibility and maintainability of the workflow.
=> Update SECRET_KEY handling in GitHub Actions workflow

GatherBuddy/AutoGather/AutoGather.cs
Reduced the distance threshold for targeting nodes from 80 to 50 units to improve accuracy and better align with player movement speed. This change enhances smoother interactions with nodes. Fine-tuned based on empirical testing.
=> Adjust node targeting distance to 50 units

GatherBuddy/AutoGather/AutoGather.Config.cs, GatherBuddy/AutoGather/AutoGather.Movement.cs, GatherBuddy/Gui/Interface.ConfigTab.cs
As of version 7.2 of the game, players can move while summoning their mount. This allows users to save entire moments of time with a mere double the pathfinding overhead.
=> Allow mounting up while moving

GatherBuddy/AutoGather/AtkReaders/GatheringMasterpieceReader.cs, GatherBuddy/AutoGather/AutoGather.Actions.cs, GatherBuddy/AutoGather/AutoGather.Collectables.cs, GatherBuddy/AutoGather/AutoGather.Var.cs
Replaced direct `AddonGatheringMasterpiece` handling with the new `GatheringMasterpieceReader` to improve readability and consistency. Updated collectable action logic, reward tier checks, and related calculations to utilize the reader interface. Simplified target score and collectability management.
=> Fix collectibles getting abandoned during revist

GatherBuddy/GatherHelper/GatherWindow.Ui.cs
- Right clicking on Auto Gather window now toggles the plugin interface.
- Updated tooltip to match new functionality.
- Tested in local, works as expected.
=> Added right click to Auto Gather window to toggle main plugin interface.
