FFXIV-CombatReborn/GatherBuddyReborn

- GatherBuddy/AutoGather/AutoGather.Actions.cs
Just a small fix for the collectable actions that were not checking the config state
> Fixed collectable actions not using config state

- GatherBuddy/AutoGather/AutoGather.Config.cs
- GatherBuddy/AutoGather/AutoGather.Movement.cs
- GatherBuddy/Gui/Interface.ConfigTab.cs
- Minimum GP to gather collectables
- Moved the collectable config to it's own category
> Added minimum GP for gathering collectables

- GatherBuddy/AutoGather/AutoGather.Config.cs
- GatherBuddy/AutoGather/AutoGather.Movement.cs
- GatherBuddy/AutoGather/AutoGather.Spiritbond.cs
- GatherBuddy/AutoGather/AutoGather.Var.cs
- GatherBuddy/Gui/Interface.ConfigTab.cs
> Add materia extraction

- GatherBuddy/AutoGather/AutoGather.Actions.cs
- GatherBuddy/AutoGather/AutoGather.Config.cs
- GatherBuddy/Gui/Interface.ConfigTab.cs
Added an option to set the minimum node level, so we can save GP when going for lower level nodes for spiritbond
> Extra options for Solid/Age node type

- GatherBuddy/AutoGather/AutoGather.ActionIDs.cs
- GatherBuddy/AutoGather/AutoGather.Actions.cs
- GatherBuddy/AutoGather/AutoGather.Config.cs
- GatherBuddy/Gui/Interface.ConfigTab.cs
Use The Giving Land and The Twelve's Bounty abilities when gathering crystals.
New mode to gather random crystals when gathering any items from regular nodes.
> Support for The Giving Land and The Twelve's Bounty abilities.

- GatherBuddy/AutoGather/AutoGather.Var.cs
> Correct item quantity calculation

- GatherBuddy/AutoGather/AutoGather.Movement.cs
- GatherBuddy/AutoGather/AutoGather.Ui.cs
- GatherBuddy/AutoGather/AutoGather.Var.cs
- GatherBuddy/AutoGather/AutoGather.cs
- GatherBuddy/AutoGather/Helpers/AdvancedUnstuck.cs
- GatherBuddy/CustomInfo/FuzzyVector3.cs
- GatherBuddy/CustomInfo/WorldData.cs
- Fine-tuning of close-to-node navigation and dismounting, also fixes spontaneous activation of Advanced Unstuck right before the node.
- Fix navigating to a wrong map marker (2nd attempt).
- Improve performance of offset lookups.
- Offsets further than 3 units away (after correction for mesh) are ignored.
> Navigation improvements

- GatherBuddy/AutoGather/AutoGather.ActionIDs.cs
- GatherBuddy/AutoGather/AutoGather.Actions.cs
- GatherBuddy/AutoGather/AutoGather.Config.cs
- GatherBuddy/Gui/Interface.ConfigTab.cs
1. Added Gatherer's Boon I, Gatherer's Boon II and Gatherer's Tidings that are usable as actions
2. Added Configurations for the above actions
3. Added a Min Boon chance required config to use above actions
> Added Gatherer's Boon Actions

- GatherBuddy/AutoGather/AutoGather.Var.cs
- GatherBuddy/AutoGather/AutoGather.cs
Check that addon IsFullyLoaded() and IsReady before using it.
> Potential fix to the MaterializeDialog flickering

- GatherBuddy/AutoGather/AutoGather.cs
- GatherBuddy/Gui/Interface.AutoGatherTab.cs
- Save auto-gather list to disk after import.
- Add a note that you can delete items from the auto-gather list using the gather window.
- Abort when gear condition is below 1%.
> QoL improvements

- GatherBuddy/AutoGather/AutoGather.cs
- GatherBuddy/AutoGather/Lists/ActiveItemList.cs
- GatherBuddy/Gui/Interface.DebugTab.cs
- GatherBuddy/Plugin/Functions.cs
- GatherBuddy/Plugin/UptimeManager.cs
Refactor auto-gathering code to enhance item prioritization, pathing, and node handling, ensuring better efficiency and accuracy. Added a debug button to populate the Diadem gatherable list for testing purposes. Improved code readability, adjusted formatting, and introduced methods for Diadem identification and node updates.
> Improve auto-gathering logic and add Diadem functionality

- GatherBuddy/AutoGather/AutoGather.Config.cs
- GatherBuddy/AutoGather/AutoGather.cs
- GatherBuddy/AutoGather/Helpers/SoundHelper.cs
- GatherBuddy/GatherBuddy.csproj
- GatherBuddy/Gui/Interface.ConfigTab.cs
- GatherBuddy/packages.lock.json
This commit migrates sound playback functionality from OpenTK to NAudio, streamlining dependencies and improving sound control. Added a volume slider for the honk sound in the config UI and adjusted corresponding logic.
> Replace OpenTK with NAudio for sound handling

- GatherBuddy/AutoGather/AutoGather.cs
Replaced visibleNodes with allPositions in the distance filtering logic for improved accuracy and consistency. This ensures the correct set of nodes is processed when determining proximity to the player.
> Refactor node distance check to use all positions.

- .github/workflows/publish.yaml
Adjusted the Docker build command to include the `--load` flag and preserved formatting for the build step command for consistency. These changes aim to enhance clarity and ensure proper workflow execution.
> Update build and Docker workflow parameters

- GatherBuddy.Web/Controllers/RateLimitFilter.cs
- GatherBuddy.Web/Program.cs
Configured `ForwardedHeadersOptions` to process `X-Forwarded-For` and `X-Forwarded-Proto` headers. Enabled middleware to handle forwarded headers, improving support for proxy environments.
> Add support for forwarded headers in HTTP requests

- GatherBuddy/AutoGather/AutoGather.Movement.cs
- GatherBuddy/AutoGather/AutoGather.cs
Should prevent illegal access of nodes caused by previous "reduction of redundancy"
> Gearset fix

- .github/workflows/publish.yaml
Renamed the `SECRET_KEY` variable to `RANDOM` across the GitHub Actions workflow files for consistency and clarity. Updated all relevant steps, environment variables, and build arguments to reflect this change. This ensures smoother integration and avoids potential ambiguities.
> Update key variable from SECRET_KEY to RANDOM in workflows

- GatherBuddy/AutoGather/AutoGather.cs
Ensure consistent targeting logic by limiting to valid gathering points and improving readability with formatting corrections. Update ECommons to the latest version for enhanced functionality.
> Fix targeting logic and update ECommons

- GatherBuddy/AutoGather/Lists/AutoGatherList.cs
Ensures the enabled state of auto-gather items is correctly synchronized, addressing potential discrepancies between configuration and runtime behavior.
> Fix enabled state synchronization for auto-gather items.

- GatherBuddy/GatherBuddy.csproj
- GatherBuddy/Gui/Interface.ConfigPresetsTab.cs
- Replaced ImGui.DragInt2 with paired ImGui.DragInt calls since Dalamud bindings no longer expose DragInt2
- Fixed inconsistent widths for input fields
> Fix Min/Max input fields
